### ISSUE TITLE
How can i use Serial?

### ISSUE THREAD

**Issue by HwangSB** [zlittell/MSF-XINPUT#15]
HI
I'm using this library, and it works really well on Windows7.
however Serial port is unable.
for example, simple code like Serial.println("hello"); was didn't work
Is there a way to use Serial Ports?

**Comment by zlittell** [comment]
You won't be able to use the built in USB serial port that is normally accessible on the Teensy.  The USB descriptors have to match the xbox 360 controller.  I usually suggest people use a serial to usb converter (FTDI chips work great or even another teensy) and just set up a regular serial port on some IO pins.
