### ISSUE TITLE
arm-none-eabi-ar file not found

### ISSUE THREAD

**Issue by robotskirts** [zlittell/MSF-XINPUT#18]
I'm not sure if this is an issue specific to this library (I don't know much about the build process.)

I fixed it by creating a symlink to arm-none-eabi-gcc-ar.

**Comment by zombierevel** [comment]
Hello, just got to this problem. Just looked in to the folder and there is no arm-none-eabi-gcc-ar. What part of the code should I update? Sorry but I am kind of noob.

**Comment by robotskirts** [comment]
Look in the arduino folder for hardware/tools/arm/bin folder

**Comment by zombierevel** [comment]
Just noticed the file I was missing was actually arm-none-eabi-ar. There is a arm-none-eabi folder with ar.exe in it, I just copied and renamed it to arm-none-eabi-ar.exe and it worked, since i dont know what this actually does hope there wont be future problems

**Comment by FourthToe** [comment]
Can confirm, changing the name allows it to compile.

**Comment by zlittell** [comment]
I have done a few reinstalls since this issue was opened and have yet been able to reproduce this issue.
