### ISSUE TITLE
Is it posible to send analog signal?

### ISSUE THREAD

**Issue by zombierevel** [zlittell/MSF-XINPUT#19]
First of all thanks to all the people involved in this project.
I am trying to adapt old wheels with teensy so they can be recognised as xbox joystics.
Not sure if I understand the code correctly but I see you send the analog values of the joystics as digital inputs. Is it posible to change the code so I can send them as analogs inputs so I can use those wheels in racing games?

**Comment by zlittell** [comment]
https://github.com/zlittell/MSF-XINPUT/blob/master/MSF%20XINPUT%20UserGuide%20V1.pdf

Look in the user guide and there is a section for the analog stick values.  The DPAD is always digital, but the sticks are analog.

What you are wanting is in the section for the stickUpdate() function
