### ISSUE TITLE
Not compatible with latest version of Teensyduino

### ISSUE THREAD

**Issue by henkv** [zlittell/MSF-XINPUT#6]
Hi! Im trying to make my own fightstick with the teensy lc but when I just replace the files there the sketches wont compile and I dont understand the code enough to get it to work on my own. 

Adding a custom usb types seems really complicated

**Comment by zlittell** [comment]
@henkv 
I just installed a fresh copy of Arduino 1.6.11 and Teensyduino 1.30
These is the latest combination I can have of these two software and it compiles fine.  Copy paste some error messages for me.

The most common overlooked thing is selecting teensylc as the board.

**Comment by zlittell** [comment]
User never replied.  Considering this issue resolved
